Make Book Hotel Project
paulshaun-kdtk/Hotel-Booking pull request #28
Opened 2024-01-27 19:37 UTC by zunairkhan811

2024-01-28 00:05 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!


Main takeaway:

- This is OPTIONAL:  You have included the frontend app as a folder in the backend app:

#### In the industry when we do different apps (a server API and a frontend app to consume it), we use different repos for each app, we never include the other app as a subfolder.  This is because an API server can serve multiple frontend apps, and also for maintainability.

#### Another option would have been to use the `react-rails` gem in order to make a single monolithic app, however, this is not the case, which is good, because the industry is quickly abandoning single monolithic apps.

#### Therefore I suggest that in the future, when you have the time, take out the `frontend-react-app` folder from the backend and put it in a new repo.  It will work just fine.



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-01-28 12:54 UTC, zunairkhan811 commented on README.md
> +```sh
@Meltrust, thanks for your suggestions, I have implemented the changes.

2024-01-28 12:58 UTC, zunairkhan811 commented on README.md
> +### Usage
@Meltrust, thanks for your suggestions, I have implemented the changes.

2024-01-28 13:07 UTC, zunairkhan811 commented on README.md
> +### Usage
@Meltrust, thanks for your suggestions, I have implemented the changes.

2024-01-28 13:08 UTC, zunairkhan811 commented on app/controllers/api/v1/reservations_controller.rb
> +      end
@Meltrust, thanks for your suggestions, I have implemented the changes.

2024-01-28 13:16 UTC, zunairkhan811 commented on frontend-react-app/src/components/AdditemForm.jsx
> +const AddItemForm = () => {
@Meltrust, thanks for your suggestions, I have implemented the changes.

2024-01-28 14:13 UTC, zunairkhan811 commented on frontend-react-app/src/components/Carousel.jsx
> +          {items.map((item) => (
@Meltrust, thanks for your suggestions, I have implemented the changes.

2024-01-28 14:14 UTC, zunairkhan811 commented on frontend-react-app/src/App.js
> +  console.log('appauthentication', isAuthenticated);
@Meltrust, thanks for your suggestions, I have implemented the changes.

2024-01-29 11:06 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Almost all tests are now passing✔️
-  Nice code organization ✔️ 
-  The app is working well✔️ 
-  Readme has been vastly improved✔️ 
-  Superfluous test folder has been removed✔️
-  Webpack compilation errors have been fixed ✔️ 
-  The app now works even if there are no items on the database ✔️ 
-  Error handling has been added to the destroy method in the controller ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-01-29 11:56 UTC, zunairkhan811 commented on README.md
> +    rspec ./spec/integration
Hi @Meltrust, thanks, Your suggestion has been implemented 😃

2024-01-29 12:13 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- All tests are now passing ✔️ 
- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2024-01-29 13:49 UTC, merged